name: TogglePlugins
author: Hancho
version: 1.0.0
main: hancho.TogglePlugins.TogglePlugins
api: [1.0.0]

commands:
    loadplugin:
     description: load Plugin
     permission: 'op'
    unloadplugin:
     description: unload plugin
     permission: 'op'
    forceunloadplugin:
     description: unload plugin without onDisable
     permission: 'op'